-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.hello
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT hello_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.hello
    OWNER to supabase_admin;

ALTER TABLE IF EXISTS public.hello
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.hello TO anon;

GRANT ALL ON TABLE public.hello TO authenticated;

GRANT ALL ON TABLE public.hello TO postgres;

GRANT ALL ON TABLE public.hello TO service_role;

GRANT ALL ON TABLE public.hello TO supabase_admin;

COMMENT ON TABLE public.hello
    IS 'hello table';
CREATE POLICY "Enable access to all users"
    ON public.hello
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);
